# Generated by Django 3.0.5 on 2020-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('instruction', models.TextField(verbose_name='질문 내용')),
                ('visualization', models.TextField(verbose_name='시각화')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
                'db_table': 'problem',
            },
        ),
    ]
